// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('/../../../../../../../lib/sources/base.js', ['zz.ui.mdl.checkbox'], [], false);
goog.addDependency('/../../../../../../../lib/sources/controllers/checkboxcontrol.js', ['zz.ui.mdl.controllers.CheckboxControl'], ['goog.dom.classlist', 'goog.events.EventType', 'goog.style', 'goog.ui.Component', 'zz.ui.mdl.controllers.BaseControl', 'zz.ui.mdl.controllers.RippleControl', 'zz.ui.mdl.views.CheckboxView'], false);
goog.addDependency('/../../../../../../../lib/sources/views/checkboxview.js', ['zz.ui.mdl.views.CheckboxView'], ['goog.dom.classlist', 'zz.ui.mdl.controllers.BaseControl'], false);
goog.addDependency('/../../../../../../../node_modules/zz.ui.mdl.ripple/lib/sources/base.js', ['zz.ui.mdl.ripple'], [], false);
goog.addDependency('/../../../../../../../node_modules/zz.ui.mdl.ripple/lib/sources/controllers/ripplecontrol.js', ['zz.ui.mdl.RippleControl'], ['goog.Timer', 'goog.dom.classlist', 'goog.events.EventType', 'goog.style', 'goog.ui.Component'], false);
goog.addDependency('/../../../../../../../node_modules/zz.ui.mdl/lib/sources/base.js', ['zz.ui.mdl'], [], false);
goog.addDependency('/../../../../../../../node_modules/zz.ui.mdl/lib/sources/controllers/basecontrol.js', ['zz.ui.mdl.controllers.BaseControl'], ['goog.events.Event', 'goog.ui.Component', 'goog.ui.Control', 'zz.i18n.services.DefaultFormatter', 'zz.models.Message', 'zz.models.enums.EventType', 'zz.ui.mdl.views.BaseView'], false);
goog.addDependency('/../../../../../../../node_modules/zz.ui.mdl/lib/sources/views/baseview.js', ['zz.ui.mdl.views.BaseView'], ['goog.ui.ControlRenderer', 'goog.ui.registry'], false);
goog.addDependency('/../../../../../../../node_modules/zz.ui.mdl/node_modules/zz.i18n/lib/sources/base.js', ['zz.i18n'], [], false);
goog.addDependency('/../../../../../../../node_modules/zz.ui.mdl/node_modules/zz.i18n/lib/sources/services/decimalformatter.js', ['zz.i18n.services.DecimalFormatter'], ['goog.i18n.NumberFormat', 'goog.i18n.NumberFormat.Format'], false);
goog.addDependency('/../../../../../../../node_modules/zz.ui.mdl/node_modules/zz.i18n/lib/sources/services/defaultformatter.js', ['zz.i18n.services.DefaultFormatter'], [], false);
goog.addDependency('/../../../../../../../node_modules/zz.ui.mdl/node_modules/zz.i18n/lib/sources/services/soymessages.js', ['zz.i18n.services.SoyMessages'], ['goog.array', 'goog.dom', 'soy'], false);
